<?php

namespace App\DataFixtures;

use App\Entity\Rencontre;
use App\Entity\User;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class AppFixtures extends Fixture
{
    public function __construct(
        private UserPasswordHasherInterface $passwordHasher
    ) {}

    public function load(ObjectManager $manager): void
    {
        // ===== USERS =====
        $admin = new User();
        $admin->setEmail('admin@football.fr');
        $admin->setUsername('Admin');
        $admin->setPassword($this->passwordHasher->hashPassword($admin, 'password123'));
        $admin->setRoles(['ROLE_ADMIN']);
        $manager->persist($admin);

        $user = new User();
        $user->setEmail('user@football.fr');
        $user->setUsername('Utilisateur');
        $user->setPassword($this->passwordHasher->hashPassword($user, 'password123'));
        $manager->persist($user);

        // ===== RENCONTRES - LIGUE DES CHAMPIONS 2024-2025 =====
        $rencontres = [

            // ========== BARRAGES ==========
            [
                'nom'     => 'Ligue des Champions - Barrages aller',
                'date'    => '2025-02-11 18:45:00',
                'lieu'    => 'Stade de Roudourou, Guingamp',
                'equipe1' => 'Stade Brestois 29',
                'equipe2' => 'Paris Saint-Germain',
                'score1'  => 0,
                'score2'  => 3,
                'journee' => 1,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages retour',
                'date'    => '2025-02-19 21:00:00',
                'lieu'    => 'Parc des Princes, Paris',
                'equipe1' => 'Paris Saint-Germain',
                'equipe2' => 'Stade Brestois 29',
                'score1'  => 7,
                'score2'  => 0,
                'journee' => 2,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages aller',
                'date'    => '2025-02-11 21:00:00',
                'lieu'    => 'City of Manchester Stadium, Manchester',
                'equipe1' => 'Manchester City',
                'equipe2' => 'Real Madrid',
                'score1'  => 2,
                'score2'  => 3,
                'journee' => 1,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages retour',
                'date'    => '2025-02-19 21:00:00',
                'lieu'    => 'Stade Santiago-Bernabéu, Madrid',
                'equipe1' => 'Real Madrid',
                'equipe2' => 'Manchester City',
                'score1'  => 3,
                'score2'  => 1,
                'journee' => 2,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages aller',
                'date'    => '2025-02-11 21:00:00',
                'lieu'    => 'Juventus Stadium, Turin',
                'equipe1' => 'Juventus FC',
                'equipe2' => 'PSV Eindhoven',
                'score1'  => 2,
                'score2'  => 1,
                'journee' => 1,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages retour',
                'date'    => '2025-02-19 21:00:00',
                'lieu'    => 'Stade Philips, Eindhoven',
                'equipe1' => 'PSV Eindhoven',
                'equipe2' => 'Juventus FC',
                'score1'  => 3,
                'score2'  => 1,
                'journee' => 2,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages aller',
                'date'    => '2025-02-11 21:00:00',
                'lieu'    => 'Estádio José Alvalade XXI, Lisbonne',
                'equipe1' => 'Sporting CP',
                'equipe2' => 'Borussia Dortmund',
                'score1'  => 0,
                'score2'  => 3,
                'journee' => 1,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages retour',
                'date'    => '2025-02-19 18:45:00',
                'lieu'    => 'Signal Iduna Park, Dortmund',
                'equipe1' => 'Borussia Dortmund',
                'equipe2' => 'Sporting CP',
                'score1'  => 0,
                'score2'  => 0,
                'journee' => 2,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages aller',
                'date'    => '2025-02-12 18:45:00',
                'lieu'    => 'Stade Jan Breydel, Bruges',
                'equipe1' => 'Club Bruges',
                'equipe2' => 'Atalanta Bergame',
                'score1'  => 2,
                'score2'  => 1,
                'journee' => 1,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages retour',
                'date'    => '2025-02-18 21:00:00',
                'lieu'    => 'Stadio Atleti Azzurri d\'Italia, Bergame',
                'equipe1' => 'Atalanta Bergame',
                'equipe2' => 'Club Bruges',
                'score1'  => 1,
                'score2'  => 3,
                'journee' => 2,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages aller',
                'date'    => '2025-02-12 21:00:00',
                'lieu'    => 'Stade Feijenoord, Rotterdam',
                'equipe1' => 'Feyenoord Rotterdam',
                'equipe2' => 'AC Milan',
                'score1'  => 1,
                'score2'  => 0,
                'journee' => 1,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages retour',
                'date'    => '2025-02-18 18:45:00',
                'lieu'    => 'Stade San Siro, Milan',
                'equipe1' => 'AC Milan',
                'equipe2' => 'Feyenoord Rotterdam',
                'score1'  => 1,
                'score2'  => 1,
                'journee' => 2,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages aller',
                'date'    => '2025-02-12 21:00:00',
                'lieu'    => 'Celtic Park, Glasgow',
                'equipe1' => 'Celtic FC',
                'equipe2' => 'Bayern Munich',
                'score1'  => 1,
                'score2'  => 2,
                'journee' => 1,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages retour',
                'date'    => '2025-02-18 21:00:00',
                'lieu'    => 'Allianz Arena, Munich',
                'equipe1' => 'Bayern Munich',
                'equipe2' => 'Celtic FC',
                'score1'  => 1,
                'score2'  => 1,
                'journee' => 2,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages aller',
                'date'    => '2025-02-12 21:00:00',
                'lieu'    => 'Stade Louis-II, Monaco',
                'equipe1' => 'AS Monaco',
                'equipe2' => 'Benfica Lisbonne',
                'score1'  => 0,
                'score2'  => 1,
                'journee' => 1,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Barrages retour',
                'date'    => '2025-02-18 21:00:00',
                'lieu'    => 'Estádio da Luz, Lisbonne',
                'equipe1' => 'Benfica Lisbonne',
                'equipe2' => 'AS Monaco',
                'score1'  => 3,
                'score2'  => 3,
                'journee' => 2,
                'saison'  => 2025,
            ],

            // ========== HUITIÈMES DE FINALE ==========
            [
                'nom'     => 'Ligue des Champions - Huitièmes aller',
                'date'    => '2025-03-05 21:00:00',
                'lieu'    => 'Parc des Princes, Paris',
                'equipe1' => 'Paris Saint-Germain',
                'equipe2' => 'Liverpool FC',
                'score1'  => 0,
                'score2'  => 1,
                'journee' => 3,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes retour',
                'date'    => '2025-03-11 21:00:00',
                'lieu'    => 'Anfield, Liverpool',
                'equipe1' => 'Liverpool FC',
                'equipe2' => 'Paris Saint-Germain',
                'score1'  => 0,
                'score2'  => 1,
                'journee' => 4,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes aller',
                'date'    => '2025-03-04 18:45:00',
                'lieu'    => 'Stade Jan Breydel, Bruges',
                'equipe1' => 'Club Bruges',
                'equipe2' => 'Aston Villa',
                'score1'  => 1,
                'score2'  => 3,
                'journee' => 3,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes retour',
                'date'    => '2025-03-12 21:00:00',
                'lieu'    => 'Villa Park, Birmingham',
                'equipe1' => 'Aston Villa',
                'equipe2' => 'Club Bruges',
                'score1'  => 3,
                'score2'  => 0,
                'journee' => 4,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes aller',
                'date'    => '2025-03-04 21:00:00',
                'lieu'    => 'Stade Santiago-Bernabéu, Madrid',
                'equipe1' => 'Real Madrid',
                'equipe2' => 'Atlético Madrid',
                'score1'  => 2,
                'score2'  => 1,
                'journee' => 3,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes retour',
                'date'    => '2025-03-12 21:00:00',
                'lieu'    => 'Estadio Metropolitano, Madrid',
                'equipe1' => 'Atlético Madrid',
                'equipe2' => 'Real Madrid',
                'score1'  => 1,
                'score2'  => 0,
                'journee' => 4,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes aller',
                'date'    => '2025-03-04 21:00:00',
                'lieu'    => 'Stade Philips, Eindhoven',
                'equipe1' => 'PSV Eindhoven',
                'equipe2' => 'Arsenal FC',
                'score1'  => 1,
                'score2'  => 7,
                'journee' => 3,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes retour',
                'date'    => '2025-03-12 21:00:00',
                'lieu'    => 'London Stadium, Londres',
                'equipe1' => 'Arsenal FC',
                'equipe2' => 'PSV Eindhoven',
                'score1'  => 2,
                'score2'  => 2,
                'journee' => 4,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes aller',
                'date'    => '2025-03-05 21:00:00',
                'lieu'    => 'Estádio da Luz, Lisbonne',
                'equipe1' => 'Benfica Lisbonne',
                'equipe2' => 'FC Barcelone',
                'score1'  => 0,
                'score2'  => 1,
                'journee' => 3,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes retour',
                'date'    => '2025-03-11 18:45:00',
                'lieu'    => 'Stade olympique Lluís-Companys, Barcelone',
                'equipe1' => 'FC Barcelone',
                'equipe2' => 'Benfica Lisbonne',
                'score1'  => 3,
                'score2'  => 1,
                'journee' => 4,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes aller',
                'date'    => '2025-03-04 21:00:00',
                'lieu'    => 'Signal Iduna Park, Dortmund',
                'equipe1' => 'Borussia Dortmund',
                'equipe2' => 'LOSC Lille',
                'score1'  => 1,
                'score2'  => 1,
                'journee' => 3,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes retour',
                'date'    => '2025-03-12 18:45:00',
                'lieu'    => 'Stade Pierre-Mauroy, Villeneuve-d\'Ascq',
                'equipe1' => 'LOSC Lille',
                'equipe2' => 'Borussia Dortmund',
                'score1'  => 1,
                'score2'  => 2,
                'journee' => 4,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes aller',
                'date'    => '2025-03-05 21:00:00',
                'lieu'    => 'Allianz Arena, Munich',
                'equipe1' => 'Bayern Munich',
                'equipe2' => 'Bayer Leverkusen',
                'score1'  => 3,
                'score2'  => 0,
                'journee' => 3,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes retour',
                'date'    => '2025-03-11 21:00:00',
                'lieu'    => 'BayArena, Leverkusen',
                'equipe1' => 'Bayer Leverkusen',
                'equipe2' => 'Bayern Munich',
                'score1'  => 0,
                'score2'  => 2,
                'journee' => 4,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes aller',
                'date'    => '2025-03-05 18:45:00',
                'lieu'    => 'Stade Feijenoord, Rotterdam',
                'equipe1' => 'Feyenoord Rotterdam',
                'equipe2' => 'Inter Milan',
                'score1'  => 0,
                'score2'  => 2,
                'journee' => 3,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Huitièmes retour',
                'date'    => '2025-03-11 21:00:00',
                'lieu'    => 'Stade Giuseppe-Meazza, Milan',
                'equipe1' => 'Inter Milan',
                'equipe2' => 'Feyenoord Rotterdam',
                'score1'  => 2,
                'score2'  => 1,
                'journee' => 4,
                'saison'  => 2025,
            ],

            // ========== QUARTS DE FINALE ==========
            [
                'nom'     => 'Ligue des Champions - Quarts aller',
                'date'    => '2025-04-09 21:00:00',
                'lieu'    => 'Parc des Princes, Paris',
                'equipe1' => 'Paris Saint-Germain',
                'equipe2' => 'Aston Villa',
                'score1'  => 3,
                'score2'  => 1,
                'journee' => 5,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Quarts retour',
                'date'    => '2025-04-15 21:00:00',
                'lieu'    => 'Villa Park, Birmingham',
                'equipe1' => 'Aston Villa',
                'equipe2' => 'Paris Saint-Germain',
                'score1'  => 3,
                'score2'  => 2,
                'journee' => 6,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Quarts aller',
                'date'    => '2025-04-08 21:00:00',
                'lieu'    => 'London Stadium, Londres',
                'equipe1' => 'Arsenal FC',
                'equipe2' => 'Real Madrid',
                'score1'  => 3,
                'score2'  => 0,
                'journee' => 5,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Quarts retour',
                'date'    => '2025-04-16 21:00:00',
                'lieu'    => 'Stade Santiago-Bernabéu, Madrid',
                'equipe1' => 'Real Madrid',
                'equipe2' => 'Arsenal FC',
                'score1'  => 1,
                'score2'  => 2,
                'journee' => 6,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Quarts aller',
                'date'    => '2025-04-09 21:00:00',
                'lieu'    => 'Stade olympique Lluís-Companys, Barcelone',
                'equipe1' => 'FC Barcelone',
                'equipe2' => 'Borussia Dortmund',
                'score1'  => 4,
                'score2'  => 0,
                'journee' => 5,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Quarts retour',
                'date'    => '2025-04-15 21:00:00',
                'lieu'    => 'Signal Iduna Park, Dortmund',
                'equipe1' => 'Borussia Dortmund',
                'equipe2' => 'FC Barcelone',
                'score1'  => 3,
                'score2'  => 1,
                'journee' => 6,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Quarts aller',
                'date'    => '2025-04-08 21:00:00',
                'lieu'    => 'Allianz Arena, Munich',
                'equipe1' => 'Bayern Munich',
                'equipe2' => 'Inter Milan',
                'score1'  => 1,
                'score2'  => 2,
                'journee' => 5,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Quarts retour',
                'date'    => '2025-04-16 21:00:00',
                'lieu'    => 'Stade Giuseppe-Meazza, Milan',
                'equipe1' => 'Inter Milan',
                'equipe2' => 'Bayern Munich',
                'score1'  => 2,
                'score2'  => 2,
                'journee' => 6,
                'saison'  => 2025,
            ],

            // ========== DEMI-FINALES ==========
            [
                'nom'     => 'Ligue des Champions - Demi-finales aller',
                'date'    => '2025-04-29 21:00:00',
                'lieu'    => 'London Stadium, Londres',
                'equipe1' => 'Arsenal FC',
                'equipe2' => 'Paris Saint-Germain',
                'score1'  => 0,
                'score2'  => 1,
                'journee' => 7,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Demi-finales retour',
                'date'    => '2025-05-07 21:00:00',
                'lieu'    => 'Parc des Princes, Paris',
                'equipe1' => 'Paris Saint-Germain',
                'equipe2' => 'Arsenal FC',
                'score1'  => 2,
                'score2'  => 1,
                'journee' => 8,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Demi-finales aller',
                'date'    => '2025-04-30 21:00:00',
                'lieu'    => 'Stade olympique Lluís-Companys, Barcelone',
                'equipe1' => 'FC Barcelone',
                'equipe2' => 'Inter Milan',
                'score1'  => 3,
                'score2'  => 3,
                'journee' => 7,
                'saison'  => 2025,
            ],
            [
                'nom'     => 'Ligue des Champions - Demi-finales retour',
                'date'    => '2025-05-06 21:00:00',
                'lieu'    => 'Stade Giuseppe-Meazza, Milan',
                'equipe1' => 'Inter Milan',
                'equipe2' => 'FC Barcelone',
                'score1'  => 4,
                'score2'  => 3,
                'journee' => 8,
                'saison'  => 2025,
            ],

            // ========== FINALE ==========
            [
                'nom'     => 'Ligue des Champions - Finale',
                'date'    => '2025-05-31 21:00:00',
                'lieu'    => 'Allianz Arena, Munich',
                'equipe1' => 'Paris Saint-Germain',
                'equipe2' => 'Inter Milan',
                'score1'  => 5,
                'score2'  => 0,
                'journee' => 9,
                'saison'  => 2025,
            ],
        ];

        foreach ($rencontres as $data) {
            $rencontre = new Rencontre();
            $rencontre->setNom($data['nom']);
            $rencontre->setDate(new \DateTime($data['date']));
            $rencontre->setLieu($data['lieu']);
            $rencontre->setEquipe1($data['equipe1']);
            $rencontre->setEquipe2($data['equipe2']);
            $rencontre->setScore1($data['score1']);
            $rencontre->setScore2($data['score2']);
            $rencontre->setJournee($data['journee']);
            $rencontre->setSaison($data['saison']);
            $manager->persist($rencontre);
        }

        $manager->flush();
    }
}
